version: '3.8'
services:
  app:
    build:
      context: .
      target: develop
    command: >
      sh -c 'poetry install --no-interaction --no-ansi -vvv --no-root ;
      poetry run python app/app.py --reload'
    restart: always
    ports:
    - 5000:5000
    volumes:
    - ./src:/srv/app
    - ./poetry.lock:/srv/poetry.lock
    - ./pyproject.toml:/srv/pyproject.toml
    environment:
      PORT: 5000
